services:
  test:
    build:
      context: test-image
    volumes:
      - ansys_inc:/usr/ansys_inc
      - ./AnsysLicenseManager/:/AnsysLicenseManager/:ro,Z
      - ./run-install.bash:/run-install.bash:ro,Z
    working_dir: /AnsysLicenseManager/linx64
    command: ["./INSTALL", "-silent", "-lm"]

volumes:
  ansys_inc:
