services:
  test:
    build:
      context: test-image
    volumes:
      - ansys_inc:/ansys_inc
      - ./AnsysLicenseManager/:/AnsysLicenseManager/:ro,Z
      - ./scratch:/scratch:rw,Z
    working_dir: /AnsysLicenseManager/linx64
    command: |
      bash -c '
        ./INSTALL -silent -LM
        cp -v -t /scratch /ansys_inc/*.err
        cp -v -t /scratch /ansys_inc/*.log
        find /ansys_inc -ls > /scratch/listing.ansys_inc.txt
        head -v -n20 /ansys_inc/*.err
        tail -v -n10 /ansys_inc/*.log
        (cd /ansys_inc/v232/licensingclient/linx64 && ./lmutil lmver lmutil)
      '

volumes:
  ansys_inc:
