services:
  rpmbuild:
    build:
      context: rpmbuild-image
    volumes:
      - rpmbuild:/root/rpmbuild:rw,Z
      - ./ansyslmd.spec:/rpmspecs/ansyslmd.spec:ro,Z
      - ./AnsysLicenseManager.tgz:/rpmsources/AnsysLicenseManager.tgz:ro,Z
      - ./builtrpms:/rpmoutputs:rw,Z

volumes:
  rpmbuild:
